# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bd70a7908ea88181d9d32a037bf4f80aa04012b6f902b7a92d4e2199e9a9ad85ea5ea6b589aad6f2eb5a0d05a5fe2f6c201082312479871f6cd2bdce8edb4e4

test:
  secret_key_base: b88438ca40d0ed27aa42f56d82be8fb27b018c6bce1a93f451bfd2679dd2cb96d06f89e5364d5f899d4b28027db194eb6974ef3757ac7b6a3ec6aa8123a6f154

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
